// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Model.Models;
using System;
using System.Collections.Generic;

namespace Model.Models.Configurations
{
    public partial class EnviosConfiguration : IEntityTypeConfiguration<Envios>
    {
        public void Configure(EntityTypeBuilder<Envios> entity)
        {
            entity.Property(e => e.Id).HasColumnName("id");

            entity.Property(e => e.Destino)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("destino");

            entity.Property(e => e.Origen)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("origen");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Envios> entity);
    }
}
