// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Model.Models;
using System;
using System.Collections.Generic;

namespace Model.Models.Configurations
{
    public partial class ProductosConfiguration : IEntityTypeConfiguration<Productos>
    {
        public void Configure(EntityTypeBuilder<Productos> entity)
        {
            entity.Property(e => e.Id).HasColumnName("ID");

            entity.Property(e => e.Articulo)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("articulo");

            entity.Property(e => e.Marca)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("marca");

            entity.Property(e => e.Precio)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("precio");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Productos> entity);
    }
}
