// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Model.Models;
using System;
using System.Collections.Generic;

namespace Model.Models.Configurations
{
    public partial class UsersConfiguration : IEntityTypeConfiguration<Users>
    {
        public void Configure(EntityTypeBuilder<Users> entity)
        {
            entity.HasIndex(e => e.Email, "UQ__Users__AB6E616496E16A40")
                .IsUnique();

            entity.HasIndex(e => e.Tel, "UQ__Users__DC107AB3B163C866")
                .IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");

            entity.Property(e => e.Dni).HasColumnName("DNI");

            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("email");

            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("nombre");

            entity.Property(e => e.Tel)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("tel");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Users> entity);
    }
}
