// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Model.Models;
using System;
using System.Collections.Generic;

namespace Model.Models.Configurations
{
    public partial class VentasConfiguration : IEntityTypeConfiguration<Ventas>
    {
        public void Configure(EntityTypeBuilder<Ventas> entity)
        {
            entity.HasKey(e => e.IdVenta)
                .HasName("PK__Ventas__459533BF7C7E7DE7");

            entity.Property(e => e.IdVenta).HasColumnName("id_venta");

            entity.Property(e => e.IdEnvio).HasColumnName("id_envio");

            entity.Property(e => e.IdProducto).HasColumnName("id_producto");

            entity.Property(e => e.IdUsuario).HasColumnName("id_usuario");

            entity.HasOne(d => d.IdEnvioNavigation)
                .WithMany(p => p.Ventas)
                .HasForeignKey(d => d.IdEnvio)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Ventas__id_envio__4222D4EF");

            entity.HasOne(d => d.IdProductoNavigation)
                .WithMany(p => p.Ventas)
                .HasForeignKey(d => d.IdProducto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Ventas__id_produ__440B1D61");

            entity.HasOne(d => d.IdUsuarioNavigation)
                .WithMany(p => p.Ventas)
                .HasForeignKey(d => d.IdUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Ventas__id_usuar__4316F928");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Ventas> entity);
    }
}
