// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models
{
    public partial class Productos
    {
        public Productos()
        {
            Variante = new HashSet<Variante>();
            Ventas = new HashSet<Ventas>();
        }

        public int Id { get; set; }
        public string Articulo { get; set; }
        public string Marca { get; set; }
        public string Precio { get; set; }

        public virtual ICollection<Variante> Variante { get; set; }
        public virtual ICollection<Ventas> Ventas { get; set; }
    }
}