// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models
{
    public partial class Users
    {
        public Users()
        {
            Ventas = new HashSet<Ventas>();
        }

        public int Id { get; set; }
        public int Dni { get; set; }
        public string Email { get; set; }
        public string Nombre { get; set; }
        public string Tel { get; set; }

        public virtual ICollection<Ventas> Ventas { get; set; }
    }
}