// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models
{
    public partial class Variante
    {
        public int Id { get; set; }
        public string Color { get; set; }
        public int IdProducto { get; set; }
        public string Talle { get; set; }

        public virtual Productos IdProductoNavigation { get; set; }
    }
}