// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models
{
    public partial class Ventas
    {
        public int IdEnvio { get; set; }
        public int IdUsuario { get; set; }
        public int IdProducto { get; set; }
        public int IdVenta { get; set; }

        public virtual Envios IdEnvioNavigation { get; set; }
        public virtual Productos IdProductoNavigation { get; set; }
        public virtual Users IdUsuarioNavigation { get; set; }
    }
}